import os
from functools import wraps

from utils.mock_db import db

from flask import Flask, request, g
from flask_cors import CORS

from nylas import APIClient
from nylas.client.restful_models import Webhook
from nylas.services.tunnel import open_webhook_tunnel


# Initialize the Nylas API client using the client id and secret specified in the .env file
nylas = APIClient(
    os.environ.get("NYLAS_CLIENT_ID"),
    os.environ.get("NYLAS_CLIENT_SECRET"),
)

# Before we start our backend, we should whitelist our frontend
# as a redirect URI to ensure the auth completes
CLIENT_URI = 'http://localhost:3000'
updated_application_details = nylas.update_application_details(redirect_uris=[CLIENT_URI])
print('Application whitelisted. Application Details: ', updated_application_details)

def run_webhook():
    """
    Run a webhook to receive real-time updates from the Nylas API.
    In this example, webhook open and error events and the messages received from the API are printed to the console.
    """
    def on_message(delta):
        """
        Raw webhook messages are parsed in the Nylas SDK and sent to this function as a delta
        """
        
        # Trigger logic on any webhook trigger Enum
        if delta["type"] == Webhook.Trigger.EVENT_CREATED:
            print(delta)

    def on_open(ws):
        print("webhook tunnel opened")

    def on_error(ws, err):
        print("Error found")
        print(err)

    open_webhook_tunnel(
        nylas, {'on_message': on_message, 'on_open': on_open, 'on_error': on_error})


# Run the webhook
run_webhook()

# Initialize the Flask app
flask_app = Flask(__name__)

# Enable CORS for the Flask app
CORS(flask_app, supports_credentials=True)


@flask_app.route("/nylas/generate-auth-url", methods=["POST"])
def build_auth_url():
    """
    Generates a Nylas Hosted Authentication URL with the given arguments. 
    The endpoint also uses the app level constant CLIENT_URI to build the URL.

    This endpoint is a POST request and accepts the following parameters in the request body:
        success_url: The URL to redirect the user to after successful authorization.
        email_address: The email address of the user who is authorizing the app.

    Returns the generated authorization URL.
    """

    request_body = request.get_json()

    # Use the SDK method to generate a Nylas Hosted Authentication URL
    auth_url = nylas.authentication_url(
        (CLIENT_URI or "") + request_body["success_url"],
        login_hint=request_body["email_address"],
        scopes=['calendar'],
        state=None,
    )

    return auth_url


@flask_app.route("/nylas/exchange-mailbox-token", methods=["POST"])
def exchange_code_for_token():
    """
    Exchanges an authorization code for an access token. 
    Once the access token is generated, it can be used to make API calls on behalf of the user. 
    For this example, we store the access token in our mock database.

    This endpoint is a POST request and accepts the following parameters: 
    
    Request Body:
        token: The authorization code generated by the Nylas Hosted Authentication.

    Returns a JSON object with the following information about the user:
        id: The identifier of the user in the database.
        emailAddress: The email address of the user.
    """

    request_body = request.get_json()

    # Use the SDK method to exchange our authorization code for an access token with the Nylas API
    access_token_obj = nylas.send_authorization(request_body["token"])

    # process the result and send to client however you want
    access_token = access_token_obj['access_token']
    email_address = access_token_obj['email_address']

    print('Access Token was generated for: ' + email_address)

    user = db.create_or_update_user(email_address, {
        'access_token': access_token,
        'email_address': email_address
    })

    return {
        'id': user['id'],
        'emailAddress': user['email_address']
    }


def is_authenticated(f):
    """
    A decorator that checks if the user is authenticated. 
    If the user is authenticated, the decorator sets the user's access token and returns the decorated function. 
    If the user is not authenticated, the decorator returns a 401 error. 

    This decorator is used for any endpoint that requires an access token to call the Nylas API.
    """

    @wraps(f)
    def decorator(*args, **kwargs):
        auth_headers = request.headers.get('Authorization')
        if not auth_headers:
            return 401

        # Find the user in the mock database
        user = db.find_user(auth_headers)
        if not user:
            return 401

        # Set the access token for the Nylas API client
        nylas.access_token = user['access_token']

        # Set the user in the Flask global object
        g.user = user

        return f(*args, **kwargs)
    return decorator


@flask_app.after_request
def after_request(response):
    """
    After request middleware that clear the Nylas access token after each request.
    """
    nylas.access_token = None

    return response


@flask_app.route('/nylas/create-events', methods=['POST'])
@is_authenticated
def create_events():
    """
    Creates an event in the authenticated user's calendar.

    This endpoint is a POST request and accepts the following parameters in the request body:

    Request Body:
        calendarId: The identifier of the calendar to create the event in.
        title: The title of the event.
        description: The description of the event.
        startTime: The start time of the event.
        endTime: The end time of the event.
        participants: A comma separated list of email addresses of the participants of the event.

    Checks if the required parameters are present in the request body.
    Creates an event object and sets the inputted parameters.
    Saves the event object to the Nylas API.

    Returns the event object.
    See our docs for more information on the Event object.
    https://developer.nylas.com/docs/api/#tag--Events
    """
    request_body = request.get_json()

    calendar_id = request_body['calendarId']
    title = request_body['title']
    description = request_body['description']
    start_time = request_body['startTime']
    end_time = request_body['endTime']
    participants = request_body['participants']

    if not calendar_id or not title or not start_time or not end_time:
        return 'Missing required fields: calendarId, title, starTime or endTime', 400

    event = nylas.events.create()

    event.title = title
    event.description = description
    event.when = {
        'start_time': start_time,
        'end_time': end_time,
    }
    event.calendar_id = calendar_id
    if participants:
        event.participants = [{"email": email}
                              for email in participants.split(", ")]

    event.save(notify_participants=True)

    return event.as_json(enforce_read_only=False)


@flask_app.route('/nylas/read-events', methods=['GET'])
@is_authenticated
def read_events():
    """
    Retrieves all events from a calendar.

    This endpoint is a GET request and accepts the following parameters:

    Query Parameters:
        calendarId: The ID of the calendar to retrieve events from.
        startsAfter: The start time of the events to retrieve.
        endsBefore: The end time of the events to retrieve.
        limit: The maximum number of events to retrieve.

    Returns a JSON array of all events from the given calendar.
    See our docs for more information on the Event object.
    https://developer.nylas.com/docs/api/#tag--Events
    """
    calendar_id = request.args.get('calendarId')
    starts_after = request.args.get('startsAfter')
    ends_before = request.args.get('endsBefore')
    limit = request.args.get('limit')

    # Use the SDK method chaining to retrieve all events from the given calendar
    # where() sets the query parameters for the request
    # all() executes the request and return the results
    res = nylas.events.where(
        calendar_id=calendar_id,
        starts_after=starts_after,
        ends_before=ends_before,
        limit=int(limit)
    ).all()

    # enforce_read_only=False is used to return the full event objects
    res_json = [item.as_json(enforce_read_only=False) for item in res]

    return res_json



@flask_app.route('/nylas/read-calendars', methods=['GET'])
@is_authenticated
def read_calendars():
    """
    Retrieves all calendars for the authenticated user.

    This endpoint is a GET request and accepts no parameters.

    Returns a JSON array of all calendars for the authenticated user.
    See our docs for more information about the calendar object.
    https://developer.nylas.com/docs/api/#tag--Calendar
    """
    res = nylas.calendars.all()

    # enforce_read_only=False is used to return the full calendar objects
    res_json = [item.as_json(enforce_read_only=False) for item in res]

    return res_json
